title: "<company name>"
labels: ["adopters"]
body:
  - type: textarea
    id: info
    attributes:
      label: "[Optional] How do you use Vul?"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "[Optional] Which targets are you scanning with Vul?"
      options:
        - label: "Container Image"
        - label: "Filesystem"
        - label: "Git Repository"
        - label: "Virtual Machine Image"
        - label: "Kubernetes"
        - label: "AWS"
        - label: "SBOM"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "[Optional] What kind of issues are scanning with Vul?"
      options:
        - label: "Software Bill of Materials (SBOM)"
        - label: "Known vulnerabilities (CVEs)"
        - label: "IaC issues and misconfigurations"
        - label: "Sensitive information and secrets"
        - label: "Software licenses"
