name: Scan
on: [push, pull_request]
jobs:
  build:
    name: Scan Go vulnerabilities
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Vul vulnerability scanner to scan for Critical Vulnerabilities
        uses: khulnasoft-lab/vul-action@master
        with:
          scan-type: 'fs'
          exit-code: '1'
          severity: 'CRITICAL'

      - name: Run Vul vulnerability scanner to scan for Medium and High Vulnerabilities
        uses: khulnasoft-lab/vul-action@master
        with:
          scan-type: 'fs'
          exit-code: '0'
          severity: 'HIGH,MEDIUM'